const Common = {
	clickedRes: "TheChoppedLeaf", 
	resIndex:0,
	restaurants:[
		{id:0, name:"TheChoppedLeaf", restFilters:["Healthy","Downtown","$$","Sale"], thumbnailUrl: require('../pages/menu/pics/TheChoppedLeaf.jpg').default, posterUrl: require('../pages/menu/pics/TheChoppedLeaf.jpg').default, footerImg:require('../pages/menu/pics/TheChoppedLeafF.jpg').default,
			descriptions:"Our chef designed menu is always made using fresh ingredients with bold, wholesome and delicious flavours. We celebrate people’s unique dietary needs and offer something for everyone. From vegan and vegetarian, to kid-friendly and gluten-friendly options, our fresh and customizable salads, bowls, wraps and soups have been designed with you in mind. Let's eat & feel good about it.",
			address:'1280 Main St W, Hamilton, ON L8S 4L8, Hamilton, Ontario', phoneNum:'905-525-9140 ext. 24323',openHours:'Mon - Thurs: 11:00am - 7:30pm\nFri: 11:00am - 5:00pm\nSat - Sun: Closed',
			menu:[{category:'full salads',foods:[{name:'bangkok',price:'$7.42',picUrl:require('../pages/menu/pics/Leaf-full-salads-0.jpg').default,desc:'Red and yellow peppers, pea pods, red onions, noodles, peanuts, and cilantro with evil peanut dressing. All salads are topped with whole wheat pita chips.'},
																			{name:'caesar',price:'$7.42',picUrl:require('../pages/menu/pics/Leaf-full-salads-1.jpg').default,desc:'Bacon bits, parmesan, and croutons with creamy caesar dressing. All salads are topped with whole wheat pita chips.'},
																			{name:'pegasus',price:'$7.42',picUrl:require('../pages/menu/pics/Leaf-full-salads-2.jpg').default,desc:'Cucumbers, red and yellow, grape tomatoes, feta, and kalamata olives with greek vinaigrette dressing. All salads are topped with whole wheat pita chips.'},
																			{name:'popeye',price:'$7.65',picUrl:require('../pages/menu/pics/Leaf-full-salads-3.jpg').default,desc:'Spinach, oranges, apples, sun-dried cranberries, roasted pecans, and feta with fruit vinaigrette. Recommended protein: prawns. Salads are topped with whole wheat pita chips.'},
																			{name:'signature',price:'$7.65',picUrl:require('../pages/menu/pics/Leaf-full-salads-4.jpg').default,desc:'Sun dried cranberries, roasted pecans, red onions, feta, and croutons with chopped balsamic dressing. All salads are topped with whole wheat pita chips.'},
																			{name:'southwest',price:'$7.42',picUrl:require('../pages/menu/pics/Leaf-full-salads-5.jpg').default,desc:'Grape tomatoes, black bean corn salsa, red and yellow peppers, cheddar, and pita chips with chipotle lime citrus dressing. All salads are topped with whole wheat pita chips.'},
																			{name:'spa',price:'$7.65',picUrl:require('../pages/menu/pics/Leaf-full-salads-6.jpg').default,desc:'Chopped mix, grape tomatoes, carrots, chickpeas, sun-dried cranberries, pumpkin seeds & chopped balsamic.'},
																			{name:'sunshine',price:'$7.65',picUrl:require('../pages/menu/pics/Leaf-full-salads-7.jpg').default,desc:'Chopped mix, cucumbers, mozzarella, avocado, and apples with goddess dressing. All salads are topped with whole wheat pita chips.'},]},
						{category:'bowls',foods:[{name:'Bowl 1',price:'$11.33',picUrl:require('../pages/menu/pics/bowls-0.jpeg').default,desc:'Black bean corn salsa, avocado, cheddar, cilantro, pita chips, and sour cream with salsa. Served on warm brown basmati rice.'},
																			{name:'Bowl 2',price:'$11.33',picUrl:require('../pages/menu/pics/bowls-1.jpeg').default,desc:'Chopped mix, roasted pecans, chickpeas, sun dried cranberries, carrots, and cucumbers with goddess dressing. Served on warm brown basmati rice.'},
																			{name:'Bowl 3',price:'$11.33',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Feta, cucumbers, grape tomatoes, red onions, and tzatziki with greek dressing. Served on warm brown basmati rice.'},
																			{name:'Bowl 4',price:'$11.33',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Romaine, grape tomatoes, real bacon bits, avocado, egg, quinoa, and ranch dressing.'}]},
						{category:'sandwiches',foods:[{name:'Spicy Chicken Sandwich',price:'$10.29',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Grilled chicken, chipotle aioli, mushrooms, red onions, and cheddar. Lightly toasted on your choice of sourdough or multigrain bread.'},
																				{name:'Cranberry Pesto Sandwich',price:'$10.29',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Grilled chicken, cranberry sauce, pesto, red and yellow peppers, cheddar, and mozzarella. Lightly toasted on your choice of sourdough or multigrain bread.'},
																				{name:'Chopped Tuna Melt Sandwich',price:'$10.29',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Tuna enhanced with creamy lemon dill, cheddar, cucumbers, and carrots. Lightly toasted on your choice of sourdough or multigrain bread.'}]},
						{category:'quesadillas',foods:[{name:'Pesto Quesadilla',price:'$11.44',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Grilled chicken, red and green peppers, cheddar, and pesto with ranch and salsa on the side.'},
																				{name:'BBQ Chicken Quesadilla',price:'$11.44',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Grilled chicken, hot peppers, cheddar, onions, mushrooms, and barbeque sauce with ranch and salsa on the side.'},
																				{name:'Baja Quesadilla',price:'$11.44',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Grilled chicken, red and green peppers, black bean corn salsa, and cheddar. Enjoy it with ranch and salsa on the side.'},
																				{name:'Vegetarian Quesadilla',price:'$11.44',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Pepper, mushrooms, red onions, sun-dried cranberries, mozzarella, and cheddar.'}]},
						
					]},
		{id:1,name:"TacoBell",restFilters:["Mexican","Westdale","$",""], thumbnailUrl: require('../pages/menu/pics/TacoBellP.jpg').default, posterUrl: require('../pages/menu/pics/TacoBellP.jpg').default, footerImg:require('../pages/menu/pics/TacoBell.jpeg').default,
			descriptions:"Taco Bell delivered to your door",
			address:'Upper James St, Hamilton, ON L9C 5R9, Hamilton, Ontario', phoneNum:'905-383-8877 ext. 24323',openHours:'Mon - Thurs: 11:00am - 7:30pm\nFri: 11:00am - 5:00pm\nSat - Sun: Closed',
			menu:[{category:'Limited Time Offer',foods:[{name:'Grande Nachos Combo',price:'$10.69',picUrl:require('../pages/menu/pics/TacoBell-LTO-0.png').default,desc:'Your choice of Grande Nachos Beef Supreme or Grande Nachos Taco Salad and a 20oz drink.'},
																									{name:'Grande Nachos - Taco Salad',price:'$9.00',picUrl:require('../pages/menu/pics/TacoBell-LTO-1.png').default,desc:'Warm tortilla chips loaded with three portions of seasoned beef, nacho cheese sauce, lettuce, tomatoes, spicy ranch sauce, crunchy red strips, and cheddar cheese.'},
																									{name:'Grande Nachos - Beef Supreme',price:'$9.00',picUrl:require('../pages/menu/pics/TacoBell-LTO-2.png').default,desc:'Warm tortilla chips loaded with three portions of seasoned beef, nacho cheese sauce, beans, and our 3-cheese blend. Topped off with cool sour cream, fresh pico de gallo and guacamole.'},
																									{name:'Loaded Taco Fries or Burrito Big Box',price:'$10.69',picUrl:require('../pages/menu/pics/TacoBell-LTO-3.png').default,desc:'Includes your choice of Loaded Taco Fries or a Loaded Taco Fries Burrito, 2 Crunchy Tacos, Cinnamon Twists and a 20oz Drink'},
																									{name:'Loaded Taco Fries Burrito',price:'$5.29',picUrl:require('../pages/menu/pics/TacoBell-LTO-4.png').default,desc:'A warm tortilla wrapped around seasoned beef, spicy ranch sauce, nacho cheese sauce, lettuce, tomatoes, cheddar cheese, and crunchy red tortilla strips.'},
																									{name:'Loaded Taco Fries',price:'$5.29',picUrl:require('../pages/menu/pics/TacoBell-LTO-5.png').default,desc:'Golden fries topped with spicy ranch sauce, nacho cheese sauce, seasoned beef, lettuce, tomatoes, cheddar cheese, and crunchy red tortilla strips.'}]},
						{category:'Combos',foods:[{name:'2 Chalupas Supreme Combo',price:'$9.99',picUrl:require('../pages/menu/pics/TacoBell-Combo-0.png').default,desc:'A crunchy and chewy flatbread filled with seasoned beef, reduced-fat sour cream, lettuce, 3-cheese blend and tomatoes. Plus regular fries and a 20oz drink.'},
																			{name:'Crunchwrap Supreme Combo',price:'$9.99',picUrl:require('../pages/menu/pics/TacoBell-Combo-1.png').default,desc:'A soft flour tortilla filled with a crunchy tostada shell, seasoned beef and nacho cheese sauce on one side with reduced-fat sour cream, lettuce and tomatoes on the other. Plus regular fries and a 20oz drink.'},
																			{name:'2 Steak Soft Tacos Combo',price:'$9.59',picUrl:require('../pages/menu/pics/TacoBell-Combo-2.png').default,desc:'A soft flour tortilla filled with grilled steak, spicy ranch sauce, lettuce, cheddar cheese and tomatoes. Plus regular fries and a drink.'},
																			{name:'2 Chicken Soft Tacos Combo',price:'$9.59',picUrl:require('../pages/menu/pics/TacoBell-Combo-3.png').default,desc:'A soft flour tortilla filled with grilled chicken, lettuce, pico de gallo and cheddar cheese. Plus regular fries and a drink.'},
																			{name:'Cheesy Gordita Crunch Combo',price:'$9.59',picUrl:require('../pages/menu/pics/TacoBell-Combo-4.png').default,desc:'A crunchy Doritos Nacho Cheese taco shell filled with seasoned beef, lettuce, Spicy Ranch sauce and cheddar cheese, all wrapped up in a grilled flatbread filled with melted 3-cheese blend. Plus regular fries and a 20oz drink.'},
																			{name:'2 Tacos Supreme Combo',price:'$9.59',picUrl:require('../pages/menu/pics/TacoBell-Combo-5.png').default,desc:'A crunchy taco shell filled with seasoned beef reduced-fat sour cream, lettuce, real cheddar cheese and tomatoes. Plus regular fries and a 20oz drink.'}]},
						{category:'Value Combos',foods:[{name:'Value Box',price:'$9.00',picUrl:require('../pages/menu/pics/TacoBell-CoCombo-0.png').default,desc:'Includes a chalupa supreme, beef crunchy taco, beef burrito, regular fries, and a 20oz drink.'},
																						{name:'Meal For Two',price:'$16.00',picUrl:require('../pages/menu/pics/TacoBell-CoCombo-1.png').default,desc:'Includes 2 beef crunchy tacos, 2 regular fries, 2 20oz drinks, and a choice of 2 crunchwrap supremes or 2 cheesy gordita crunch or 1 of each. Calories: 970-1330/serving'},
																						{name:'$25 Variety Pack',price:'$25.00',picUrl:require('../pages/menu/pics/TacoBell-CoCombo-2.png').default,desc:'Includes 4 beef crunchy tacos, 4 beef burritos, 2 fries supreme and 2 cinnamon twists. Calories: 570 calories/Serving. (Serves 6)'}]},
						{category:'Party Pack',foods:[{name:'Crunchy Tacos Party Pack',price:'$26.59',picUrl:require('../pages/menu/pics/TacoBell-PP-0.png').default,desc:'10 Crunchy Tacos, 2 regular fries, and 2 chips and nacho cheese sauce (Serves 5) Calories: 550/per serving'},
																					{name:'Doritos Tacos Party Pack',price:'$29.09',picUrl:require('../pages/menu/pics/TacoBell-PP-1.jpeg').default,desc:'10 Doritos Locos Tacos, 2 regular fries, and 2 chips and nacho cheese sauce. (Serves 5) Calories: 540/ per serving'},
																					{name:'Supreme Tacos Party Pack',price:'$29.59',picUrl:require('../pages/menu/pics/TacoBell-PP-0.png').default,desc:'10 Crunchy Tacos Supreme, 2 regular fries, and 2 chips and nacho cheese sauce. (Serves 5) Calories: 600/ per serving'}]},
						]},
		{id:2,name:"Saigon",restFilters:["Asian","Westdale","$$",""], thumbnailUrl: require('../pages/menu/pics/Saigon.jpeg').default, posterUrl: require('../pages/menu/pics/Saigon-poster.jpg').default, footerImg:require('../pages/menu/pics/Saigon-poster.jpg').default,
			descriptions:"Vietnamese  Noodles  Healthy  Asian Fusion  Vegetarian  Bubble Tea",
			address:'1024 King St W, Hamilton, ON L8S 1L5, Hamilton, Ontario', phoneNum:'905-528-1096 ext. 24323',openHours:'Mon - Thurs: 11:00am - 7:30pm\nFri: 11:00am - 5:00pm\nSat - Sun: Closed',
			menu:[{category:'Starters',foods:[{name:'Spring Roll (2 pcs)',price:'$4.99', picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Vegetarian spring rolls option. Deep fried spring rolls with pork shrimp, taro, and onion stuffing. Served with traditional Vietnamese fish sauce.'},
																				{name:'Summer Rolls (2 pcs)',price:'$4.99',picUrl:require('../pages/menu/pics/Saigon-starter-0.jpeg').default,desc:'Vegetarian tofu option. Rice paper wraps with vermicelli, lettuce, pork, and shrimp. Served with traditional hoisin peanut sauce.'},
																				{name:'BBQ Pork Rolls (2 pcs)',price:'$4.99',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Rice paper wraps with vermicelli, lettuce, and sliced BBQ pork. Served with traditional Vietnamese fish sauce.'},
																				{name:'Shredded Pork Skin Rolls (2 pcs)',price:'$4.99',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Rice paper wraps with vermicelli, lettuce, and shredded pork skin. Served with traditional Vietnamese fish sauce.'},
																				{name:'Wonton Soup',price:'$4.99',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Handmade shrimp, pork wontons, and served in our house broth. Garnished with mixed onions.'},
																				{name:'Breaded Shrimp (10pcs)',price:'$9.99',picUrl:require('../pages/menu/pics/Saigon-starter-1.jpeg').default,desc:'Deep fried and breaded shrimp.'},
																				{name:'Mango Salad',price:'$10.99',picUrl:require('../pages/menu/pics/Saigon-starter-2.jpeg').default,desc:'Fresh sliced mangos with red onions green and red peppers. Topped with roasted cashews and a sweet dressing.'}]},
						{category:'Pho Soups',foods:[{name:'Tofu Pho',price:'$9.99',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'A unique blend of tofu, broccoli, Napa cabbage, bok choy, and carrots. Garnished with a mix of green and white onions.'},
																				{name:'Rare Beef Pho',price:'$9.99',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Sliced rare beef - cooks when simmered in broth. Garnished with a mix of green and white onions.'},
																				{name:'Well Done Beef Pho',price:'$9.99',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Garnished with a mix of green and white onions.'},
																				{name:'Rare Beef and Well Done Beef Pho',price:'$9.99',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Garnished with a mix of green and white onions.'},
																				{name:'Beef Ball Pho',price:'$9.99',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Garnished with a mix of green and white onions.'},
																				{name:'Special Combination Pho',price:'$10.99',picUrl:require('../pages/menu/pics/Saigon-phoSo-0.jpeg').default,desc:'A combination of sliced rare beef, well done beef, beef balls, tendon, and tripe. Garnished with a mix of green and white onions.'}]},
						{category:'Chicken Stir Fry Dishes',foods:[{name:'Chicken and Broccoli',price:'$14.49',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Sliced chicken breast and broccoli. Served with a bowl of white jasmine rice.'},
																											{name:'Chicken and Snow Peas',price:'$14.49',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Sliced chicken breast and snow peas. Served with a bowl of white jasmine rice.'},
																											{name:'Chicken and Ginger',price:'$14.49',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Sliced chicken breast and ginger with onions. Served with a bowl of white jasmine rice.'}]},
						{category:'Assorted Stir Fry Dishes',foods:[{name:'Beef and Mixed Vegetables',price:'$12.99',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'A plate of beef with a variety of mixed vegetables (broccoli, carrots, bok choy, Napa cabbage, and onions), served with white jasmine rice.'},
																					{name:'Chicken and Mixed Vegetables',price:'$12.99',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'A plate of chicken with a variety of mixed vegetables (broccoli, carrots, bok choy, Napa cabbage, and onions), served with white jasmine rice.'},
																					{name:'Shrimp and Mixed Vegetables',price:'$13.99',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'A plate of shrimp with a variety of mixed vegetables (broccoli, carrots, bok choy, Napa cabbage, and onions), served with white jasmine rice.'}]},
						{category:'Plated Rice Dishes',foods:[{name:'Grilled Lemongrass Pork Chop',price:'$11.49',picUrl:require('../pages/menu/pics/Saigon-PRD-0.jpg').default,desc:'Grilled marinated pork chops served with white jasmine rice.'},
																									{name:'Grilled Lemongrass Beef and Fried Egg',price:'$11.49',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Grilled marinated beef and fried egg. Served with white jasmine rice.'},
																									{name:'Grilled Lemongrass Chicken and Fried Egg',price:'$11.49',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'Grilled marinated chicken and fried egg served with white jasmine rice.'}]},
						{category:'Vermicelli',foods:[{name:'Sliced Grilled Pork Chops on Vermicelli',price:'$11.49',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:''},
																					{name:'Seasoned Vietnamese Sausage on Vermicelli',price:'$11.49',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:''},
																					{name:'Grilled Pork Chops and Vietnamese Sausage on Vermicelli',price:'$11.49',picUrl:require('../pages/menu/pics/Saigon-V-0.jpeg').default,desc:''}]},
						{category:'Rice Noodles or Udon Noodles',foods:[{name:'Pad Thai',price:'$13.49',picUrl:require('../pages/menu/pics/Saigon-RN-0.jpeg').default,desc:'This dish is garnished with peanuts and a lime wedge.'},
																													{name:'Seafood and Mixed Vegetables',price:'$14.99',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'A plate of shrimp, squid, crab stick, and fish balls with a variety of mixed vegetables (broccoli, carrots, bok choy, Napa cabbage, and onions).'},
																													{name:'Beef and Mixed Vegetables',price:'$14.49',picUrl:require('../pages/menu/pics/nonepic.jpg').default,desc:'A plate of beef with a variety of mixed vegetables (broccoli, carrots, bok choy, Napa cabbage, and onions).'}]},
						
						]},
		{id:3,name:"Bistro",restFilters:["All","Campus","$$",""],  thumbnailUrl: require('../pages/menu/pics/East-Meets-West-Bistro.jpg').default, posterUrl: require('../pages/menu/pics/East-Meets-West-Bistro.jpg').default,footerImg:require('../pages/menu/pics/East-Meets-West-Bistro.jpg').default,
				descriptions:"East Meets West embraces the use of local, sustainable and ocean-friendly ingredients to bring you fresh and delicious meals from all over the world. The Bistro is set in a two-story glass atrium, allowing for lots of natural lighting that creates a warm and welcoming atmosphere.",
				address:'1280 Main St W, Hamilton, ON L8S 4L8, Hamilton, Ontario', phoneNum:'905-525-9140 ext. 26500',openHours:'Mon - Thurs: 11:00am - 7:30pm\nFri: 11:00am - 5:00pm\nSat - Sun: Closed',
				menu:[{category:'',foods:[{name:'',picUrl:'',desc:''}]}]},
		{id:4,name:"Valentino's Restaurant",restFilters:["Italian","Westdale","$$$",""], thumbnailUrl: require('../pages/menu/pics/Valentino.jpg').default, posterUrl: require('../pages/menu/pics/Valentino.jpg').default,footerImg:require('../pages/menu/pics/Valentino.jpg').default,
				descriptions:"",
				address:'823 King St W, Hamilton, ON L8S 4L8, Hamilton, Ontario', phoneNum:'905-523-4240 ext. ',openHours:'Mon - Thurs: 11:00am - 7:30pm\nFri: 11:00am - 5:00pm\nSat - Sun: Closed',
				menu:[{category:'',foods:[{name:'',picUrl:'',desc:''}]}]},
		{id:5,name:"KenzoRamen",restFilters:["Japanese","Downtown","$$",""],thumbnailUrl: require('../pages/menu/pics/KenzoRamen.jpeg').default, posterUrl: require('../pages/menu/pics/KenzoRamen.jpeg').default,footerImg:require('../pages/menu/pics/KenzoRamen.jpeg').default,
				descriptions:"Noodles made fresh in-house",
				address:'21 King St E, Hamilton, ON L8N 1A1, Hamilton, Ontario', phoneNum:'905-577-6666 ext.',openHours:'Mon - Thurs: 11:00am - 7:30pm\nFri: 11:00am - 5:00pm\nSat - Sun: Closed',
				menu:[{category:'',foods:[{name:'',picUrl:'',desc:''}]}]},
		{id:6,name:"DragonCourt",restFilters:["Asian","Westdale","$$$",""],thumbnailUrl: require('../pages/menu/pics/DragonCourt.jpg').default, posterUrl: require('../pages/menu/pics/DragonCourt.jpg').default,footerImg:require('../pages/menu/pics/DragonCourt.jpg').default,
				descriptions:"In Dragon Court you will be able to try the two most distinctive types of Chinese Cuisine ��Cantonese & Szechuan. Our owner and chef, Wing, will suprise you from time to time with creative new dishes!",
				address:'988 King St W, Hamilton, ON L8S 1L1, Hamilton, Ontario', phoneNum:'905-522-1999 ext. ',openHours:'Mon - Thurs: 11:00am - 7:30pm\nFri: 11:00am - 5:00pm\nSat - Sun: Closed',
				menu:[{category:'',foods:[{name:'',picUrl:'',desc:''}]}]},
		{id:7,name:"McDonalds",restFilters:["Fast Food","Westdale","$",""], thumbnailUrl: require('../pages/menu/pics/McDonaldF.jpg').default, posterUrl: require('../pages/menu/pics/McDonald.jpg').default, footerImg:require('../pages/menu/pics/McDonaldF.jpg').default,
				descriptions:"The health and well-being of our crew and guests has always been important to us. To support social distancing and ensure the best possible experience for our crew and guests, we are simplifying our menu by temporarily removing some items. A full range of our classic products and favourites are still available for you to enjoy.",
				address:'50 Dundurn St S, Hamilton, ON L8S 4L8, Hamilton, Ontario', phoneNum:'905-577-1027 ext. ',openHours:'Mon - Thurs: 24 hours\nFri: 24 hours\nSat - Sun: 24 hours',
				menu:[{category:'Burger Meals',foods:[{name:'Big Mac Extra Value Meal [710-1140 Cals]',price:'$10.99',picUrl:require('../pages/menu/pics/McDonald-BurMea-0.png').default,desc:''},
																							{name:'Double Big Mac Extra Value Meal [870-1300 Cals]',price:'$12.99',picUrl:require('../pages/menu/pics/McDonald-BurMea-1.png').default,desc:''},
																							{name:'Big Mac (No Meat) Extra Value Meal [540-970 Cals]',price:'$9.69',picUrl:require('../pages/menu/pics/McDonald-BurMea-2.png').default,desc:''},
																							{name:'Quarter Pounder with Cheese Extra Value Meal [670-1100 Cals]',price:'$10.99',picUrl:require('../pages/menu/pics/McDonald-BurMea-3.png').default,desc:''},
																							{name:'Quarter Pounder BLT Extra Value Meal [750-1180 Cals]',price:'$11.89',picUrl:require('../pages/menu/pics/McDonald-BurMea-4.png').default,desc:''},
																							{name:'Quarter Pounder without Cheese Extra Value Meal [570-1000 Cals]',price:'$10.19',picUrl:require('../pages/menu/pics/McDonald-BurMea-5.png').default,desc:''},
																							{name:'Double Quarter Pounder with Cheese Extra Value Meal [890-1320 Cals]',price:'$12.99',picUrl:require('../pages/menu/pics/McDonald-BurMea-6.png').default,desc:''},
																							{name:'Double Quarter Pounder BLT Extra Value Meal [990-1430 Cals]',price:'$13.59',picUrl:require('../pages/menu/pics/McDonald-BurMea-7.png').default,desc:''},
																							{name:'Double Quarter Pounder without Cheese Extra Value Meal [790-1220 Cals]',price:'$12.39',picUrl:require('../pages/menu/pics/McDonald-BurMea-8.png').default,desc:''},
																							{name:'Double Cheeseburger Extra Value Meal [560-990 Cals]',price:'$8.49',picUrl:require('../pages/menu/pics/McDonald-BurMea-9.png').default,desc:''},
																							{name:'McPicks McDouble Meal [520-950 Cals]',price:'$6.29',picUrl:require('../pages/menu/pics/McDonald-BurMea-10.png').default,desc:''},
																							]},
							{category:'Chicken & Fish',foods:[{name:'BLT with Crispy Chicken Extra Value Meal [830-1260 Cals]',price:'$12.59',picUrl:require('../pages/menu/pics/McDonald-ChiFis-0.png').default,desc:''},
																								{name:'BLT with Grilled Chicken Extra Value Meal [700-1130 Cals]',price:'$12.59',picUrl:require('../pages/menu/pics/McDonald-ChiFis-1.png').default,desc:''},
																								{name:'Spicy Habanero McChicken Extra Value Meal [610-1040 Cals]',price:'$11.19',picUrl:require('../pages/menu/pics/McDonald-ChiFis-2.png').default,desc:''},
																								{name:'McChicken Extra Value Meal [620-1052 Cals]',price:'$10.99',picUrl:require('../pages/menu/pics/McDonald-ChiFis-3.png').default,desc:''},
																								{name:'6 McNuggets Extra Value Meal [450-880 Cals]',price:'$10.99',picUrl:require('../pages/menu/pics/McDonald-ChiFis-4.png').default,desc:''},
																								{name:'10 McNuggets Extra Value Meal [670-1102 Cals]',price:'$12.99',picUrl:require('../pages/menu/pics/McDonald-ChiFis-5.png').default,desc:''},
																								{name:'Filet-O-Fish Extra Value Meal [540-970 Cals]',price:'$10.99',picUrl:require('../pages/menu/pics/McDonald-ChiFis-6.png').default,desc:''},
																								{name:'Double Filet-O-Fish Extra Value Meal [710-1140 Cals]',price:'$12.69',picUrl:require('../pages/menu/pics/McDonald-ChiFis-7.png').default,desc:''},
																								{name:'McPicks Junior Chicken Meal [520-952 Cals]',price:'$6.29',picUrl:require('../pages/menu/pics/McDonald-ChiFis-8.png').default,desc:''}]},
							{category:'All Day Breakfast',foods:[{name:'Hotcakes & Bacon [670.0 Cals]',price:'$6.29',picUrl:require('../pages/menu/pics/McDonald-ADBre-0.png').default,desc:''},
																									{name:'Hotcakes & Bacon Extra Value Meal [830.0 Cals]',price:'$7.79',picUrl:require('../pages/menu/pics/McDonald-ADBre-1.png').default,desc:''},
																									{name:'Hotcakes [350.0 Cals]',price:'$4.39',picUrl:require('../pages/menu/pics/McDonald-ADBre-2.png').default,desc:''},
																									{name:'Hotcakes Extra Value Meal [760.0 Cals]',price:'$6.89',picUrl:require('../pages/menu/pics/McDonald-ADBre-3.png').default,desc:''},
																									]},
							{category:'Happy Meals',foods:[{name:'Happy Meal Hamburger with Mini Fry [390-500 Cals]',price:'$4.39',picUrl:require('../pages/menu/pics/McDonald-HapMea-0.png').default,desc:''},
																						{name:'Happy Meal Hamburger with Apple Slices [310-420 Cals]',price:'$4.39',picUrl:require('../pages/menu/pics/McDonald-HapMea-1.png').default,desc:''},
																						{name:'Happy Meal Hamburger with Small Fries [510-620 Cals]',price:'$4.39',picUrl:require('../pages/menu/pics/McDonald-HapMea-2.png').default,desc:''},
																						{name:'Happy Meal Cheeseburger with Mini Fries [440-550 Cals]',price:'$4.99',picUrl:require('../pages/menu/pics/McDonald-HapMea-3.png').default,desc:''},
																						{name:'Happy Meal Cheeseburger with Apple Slices [360-470 Cals]',price:'$4.99',picUrl:require('../pages/menu/pics/McDonald-HapMea-4.png').default,desc:''},
																						{name:'Happy Meal Cheeseburger with Small Fries [560-670 Cals]',price:'$4.99',picUrl:require('../pages/menu/pics/McDonald-HapMea-5.png').default,desc:''},
																						{name:'Happy Meal Crispy Chicken Snack Wrap with Apple Slices [360-470 Cals]',price:'$4.99',picUrl:require('../pages/menu/pics/McDonald-HapMea-6.png').default,desc:''},
																						{name:'Happy Meal Grilled Chicken Snack Wrap with Apple Slices [290-400 Cals]',price:'$4.99',picUrl:require('../pages/menu/pics/McDonald-HapMea-7.png').default,desc:''},
																						{name:'Happy Meal 4 McNuggets with Mini Fries [360-490 Cals]',price:'$5.29',picUrl:require('../pages/menu/pics/McDonald-HapMea-8.png').default,desc:''},
																						{name:'Happy Meal 4 McNuggets with Apple Slices [280-410 Cals]',price:'$5.29',picUrl:require('../pages/menu/pics/McDonald-HapMea-9.png').default,desc:''},
																						{name:'Happy Meal 4 McNuggets with Small Fries [480-610 Cals]',price:'$5.29',picUrl:require('../pages/menu/pics/McDonald-HapMea-10.png').default,desc:''},
																						{name:'Happy Meal Hotcakes with Mini Fry [500-610 Cals]',price:'$4.49',picUrl:require('../pages/menu/pics/McDonald-HapMea-11.png').default,desc:''},
																						{name:'Happy Meal Hotcakes with Small Fries [620-730 Cals]',price:'$4.59',picUrl:require('../pages/menu/pics/McDonald-HapMea-12.png').default,desc:''},
																						{name:'Happy Meal Hotcakes with Apples [420-530 Cals]',price:'$4.49',picUrl:require('../pages/menu/pics/McDonald-HapMea-13.png').default,desc:''},
																						]},
							{category:'Wraps',foods:[{name:'Ranch Chicken Snack Wrap with Grilled Chicken [250.0 Cals]',price:'$3.09',picUrl:require('../pages/menu/pics/McDonald-Wra-0.png').default,desc:''},
																			{name:'Ranch Chicken Snack Wrap with Crispy Chicken [320.0 Cals]',price:'$3.09',picUrl:require('../pages/menu/pics/McDonald-Wra-1.png').default,desc:''},
																			]},
							{category:'Hot Drinks',foods:[{name:'Premium Roast Brewed Coffee [3.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-HotDri-0.png').default,desc:''},
																						{name:'Premium Roast Decaf Coffee [0.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-HotDri-1.png').default,desc:''},
																						{name:'Orange Pekoe Tea [0.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-HotDri-2.png').default,desc:''},
																						{name:'Earl Grey Tea [0.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-HotDri-3.png').default,desc:''},
																						{name:'Green Tea [0.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-HotDri-4.png').default,desc:''},
																						{name:'Peppermint Tea [0.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-HotDri-5.png').default,desc:''},
																						{name:'Premium Roast Coffee Carafe (Serves 12) [720-760 Cals]',price:'$17.59',picUrl:require('../pages/menu/pics/McDonald-HotDri-6.png').default,desc:''},
																						{name:'Premium Roast Decaf Coffee Carafe (Serves 12) [720-760 Cals]',price:'$17.59',picUrl:require('../pages/menu/pics/McDonald-HotDri-7.png').default,desc:''},
																						{name:'Sugar Free Vanilla Latte (2% Milk) [120.0 Cals]',price:'$3.39',picUrl:require('../pages/menu/pics/McDonald-HotDri-8.png').default,desc:''},
																						]},
							{category:'Cold Drinks',foods:[{name:'Coca-Cola [100.0 Cals]',price:'$1.49',picUrl:require('../pages/menu/pics/McDonald-ColDri-0.png').default,desc:''},
																						{name:"Barq's Root Beer [110.0 Cals]",price:'$1.49',picUrl:require('../pages/menu/pics/McDonald-ColDri-1.png').default,desc:''},
																						{name:'Sprite [100.0 Cals]',price:'$1.49',picUrl:require('../pages/menu/pics/McDonald-ColDri-2.png').default,desc:''},
																						{name:'Diet Coke [1.0 Cals]',price:'$1.49',picUrl:require('../pages/menu/pics/McDonald-ColDri-3.png').default,desc:''},
																						{name:'NESTEA Iced Tea [80.0 Cals]',price:'$1.49',picUrl:require('../pages/menu/pics/McDonald-ColDri-4.png').default,desc:''},
																						{name:'Fruitopia Strawberry [90.0 Cals]',price:'$1.49',picUrl:require('../pages/menu/pics/McDonald-ColDri-5.png').default,desc:''},
																						{name:'Fruitopia Orange [90.0 Cals]',price:'$1.49',picUrl:require('../pages/menu/pics/McDonald-ColDri-6.png').default,desc:''},
																						{name:'Coke Zero [1.0 Cals]',price:'$1.49',picUrl:require('../pages/menu/pics/McDonald-ColDri-7.png').default,desc:''},
																						{name:'Iced Coffee [120.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-ColDri-8.png').default,desc:''},
																						{name:'Vanilla Iced Coffee [100.0 Cals]',price:'$2.09',picUrl:require('../pages/menu/pics/McDonald-ColDri-9.png').default,desc:''},
																						{name:'Caramel Iced Coffee [100.0 Cals]',price:'$2.09',picUrl:require('../pages/menu/pics/McDonald-ColDri-10.png').default,desc:''},
																						{name:'Sugar Free Vanilla Iced Coffee [60.0 Cals]',price:'$2.09',picUrl:require('../pages/menu/pics/McDonald-ColDri-11.png').default,desc:''},
																						{name:'Dasani Water [0.0 Cals]',price:'$2.39',picUrl:require('../pages/menu/pics/McDonald-ColDri-12.png').default,desc:''},
																						{name:'Orange Juice [110.0 Cals]',price:'$2.39',picUrl:require('../pages/menu/pics/McDonald-ColDri-13.png').default,desc:''},
																						{name:'Apple Juice [110.0 Cals]',price:'$2.39',picUrl:require('../pages/menu/pics/McDonald-ColDri-14.png').default,desc:''},
																						{name:'1% Milk Bottle [110.0 Cals]',price:'$1.89',picUrl:require('../pages/menu/pics/McDonald-ColDri-15.png').default,desc:''},
																						{name:'Chocolate Milk Bottle [170.0 Cals]',price:'$1.89',picUrl:require('../pages/menu/pics/McDonald-ColDri-16.png').default,desc:''},
																						{name:'Vanilla Triple Thick Milkshake [530.0 Cals]',price:'$3.49',picUrl:require('../pages/menu/pics/McDonald-ColDri-17.png').default,desc:''},
																						{name:'Chocolate Triple Thick Milkshake [560.0 Cals]',price:'$3.49',picUrl:require('../pages/menu/pics/McDonald-ColDri-18.png').default,desc:''},
																						{name:'Strawberry Triple Thick Milkshake [540.0 Cals]',price:'$3.49',picUrl:require('../pages/menu/pics/McDonald-ColDri-19.png').default,desc:''},
																						]},
							{category:'Bakery',foods:[{name:'Strawberry Pie [230.0 Cals]',price:'$1.39',picUrl:require('../pages/menu/pics/McDonald-Bak-0.png').default,desc:''},
																				{name:'Baked Apple Pie [270.0 Cals]',price:'$1.39',picUrl:require('../pages/menu/pics/McDonald-Bak-1.png').default,desc:''},
																				{name:'Apple & Strawberry Pie [500.0 Cals]',price:'$1.99',picUrl:require('../pages/menu/pics/McDonald-Bak-2.png').default,desc:''},
																				{name:'2 Strawberry Pies [460.0 Cals]',price:'$1.99',picUrl:require('../pages/menu/pics/McDonald-Bak-3.png').default,desc:''},
																				{name:'2 Baked Apple Pies [540.0 Cals]',price:'$1.99',picUrl:require('../pages/menu/pics/McDonald-Bak-4.png').default,desc:''},
																				{name:'Banana Chocolate Chunk Muffin [430.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-Bak-5.png').default,desc:''},
																				{name:'Banana Chocolate Chunk Muffin Pairing [430.0 Cals]',price:'$2.39',picUrl:require('../pages/menu/pics/McDonald-Bak-6.png').default,desc:''},
																				{name:'Blueberry Muffin [430.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-Bak-7.png').default,desc:''},
																				{name:'Blueberry Muffin Pairing [430.0 Cals]',price:'$2.39',picUrl:require('../pages/menu/pics/McDonald-Bak-8.png').default,desc:''},
																				{name:'Fruit & Fibre Muffin [380.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-Bak-9.png').default,desc:''},
																				{name:'Fruit & Fibre Muffin Pairing [380.0 Cals]',price:'$2.39',picUrl:require('../pages/menu/pics/McDonald-Bak-10.png').default,desc:''},
																				{name:'Carrot Muffin [430.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-Bak-11.png').default,desc:''},
																				{name:'Carrot Muffin Pairing [430.0 Cals]',price:'$2.39',picUrl:require('../pages/menu/pics/McDonald-Bak-12.png').default,desc:''},
																				{name:'Cranberry Orange Muffin [360.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-Bak-13.png').default,desc:''},
																				{name:'Cranberry Orange Muffin Pairing [360.0 Cals]',price:'$2.39',picUrl:require('../pages/menu/pics/McDonald-Bak-14.png').default,desc:''},
																				{name:'6 Baked Muffins [360-430 Cals]',price:'$7.69',picUrl:require('../pages/menu/pics/McDonald-Bak-15.png').default,desc:''},
																				{name:'Brownie Cookie [140.0 Cals]',price:'$1.09',picUrl:require('../pages/menu/pics/McDonald-Bak-16.png').default,desc:''},
																				{name:'Chocolate Chunk Cookie [160.0 Cals]',price:'$1.09',picUrl:require('../pages/menu/pics/McDonald-Bak-17.png').default,desc:''},
																				{name:'2 RMHC Cookies [300-320 Cals]',price:'$1.59',picUrl:require('../pages/menu/pics/McDonald-Bak-18.png').default,desc:''},
																				{name:'6 RMHC Cookies [900-960 Cals]',price:'$4.39',picUrl:require('../pages/menu/pics/McDonald-Bak-19.png').default,desc:''},
																				{name:'12 RMHC Cookies [1800-1920 Cals]',price:'$8.19',picUrl:require('../pages/menu/pics/McDonald-Bak-19.png').default,desc:''},
																				]},
							{category:'Sweets & Treats',foods:[{name:'Oreo McFlurry [330.0 Cals]',price:'$3.29',picUrl:require('../pages/menu/pics/McDonald-SweTre-0.png').default,desc:''},
																								{name:'M&M McFlurry [410.0 Cals]',price:'$3.29',picUrl:require('../pages/menu/pics/McDonald-SweTre-1.png').default,desc:''},
																								{name:'Skor McFlurry [370.0 Cals]',price:'$3.29',picUrl:require('../pages/menu/pics/McDonald-SweTre-2.png').default,desc:''},
																								{name:'Fudge Sundae [340.0 Cals]',price:'$3.19',picUrl:require('../pages/menu/pics/McDonald-SweTre-3.png').default,desc:''},
																								{name:'Caramel Sundae [340.0 Cals]',price:'$3.19',picUrl:require('../pages/menu/pics/McDonald-SweTre-4.png').default,desc:''},
																								]},
							{category:'Snacks & Sides',foods:[{name:'French Fries [240.0 Cals]',price:'$2.19',picUrl:require('../pages/menu/pics/McDonald-SnaSid-0.png').default,desc:''},
																								{name:'Banana Chocolate Chunk Muffin [430.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-SnaSid-1.png').default,desc:''},
																								{name:'Banana Chocolate Chunk Muffin Pairing [430.0 Cals]',price:'$3.29',picUrl:require('../pages/menu/pics/McDonald-SnaSid-2.png').default,desc:''},
																								{name:'Fruit & Fibre Muffin [380.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-SnaSid-3.png').default,desc:''},
																								{name:'Cranberry Orange Muffin Pairing [360.0 Cals]',price:'$2.39',picUrl:require('../pages/menu/pics/McDonald-SnaSid-4.png').default,desc:''},
																								{name:'Apple Slices [40.0 Cals]',price:'$1.69',picUrl:require('../pages/menu/pics/McDonald-SnaSid-5.png').default,desc:''},
																								]},
							{category:'Individual Items',foods:[{name:'Big Mac [560.0 Cals]',price:'$6.79',picUrl:require('../pages/menu/pics/McDonald-Ind-0.png').default,desc:''},
																									{name:'Double Big Mac [730.0 Cals]',price:'$8.79',picUrl:require('../pages/menu/pics/McDonald-Ind-1.png').default,desc:''},
																									{name:'Big Mac, No Meat [400.0 Cals]',price:'$5.49',picUrl:require('../pages/menu/pics/McDonald-Ind-2.png').default,desc:''},
																									{name:'Quarter Pounder With Cheese [530.0 Cals]',price:'$6.79',picUrl:require('../pages/menu/pics/McDonald-Ind-3.png').default,desc:''},
																									{name:'Quarter Pounder BLT [610.0 Cals]',price:'$7.69',picUrl:require('../pages/menu/pics/McDonald-Ind-4.png').default,desc:''},
																									{name:'Quarter Pounder without Cheese [430.0 Cals]',price:'$5.99',picUrl:require('../pages/menu/pics/McDonald-Ind-5.png').default,desc:''},
																									{name:'Double Quarter Pounder With Cheese [750.0 Cals]',price:'$8.79',picUrl:require('../pages/menu/pics/McDonald-Ind-6.png').default,desc:''},
																									{name:'Double Quarter Pounder BLT [830.0 Cals]',price:'$8.39',picUrl:require('../pages/menu/pics/McDonald-Ind-7.png').default,desc:''},
																									{name:'Double Quarter Pounder without Cheese [650.0 Cals]',price:'$8.19',picUrl:require('../pages/menu/pics/McDonald-Ind-8.png').default,desc:''},
																									{name:'Double Cheeseburger [420.0 Cals]',price:'$3.29',picUrl:require('../pages/menu/pics/McDonald-Ind-9.png').default,desc:''},
																									{name:'Double Hamburger [320.0 Cals]',price:'$2.69',picUrl:require('../pages/menu/pics/McDonald-Ind-10.png').default,desc:''},
																									{name:'Cheeseburger [290.0 Cals]',price:'$2.59',picUrl:require('../pages/menu/pics/McDonald-Ind-11.png').default,desc:''},
																									{name:'Hamburger [240.0 Cals]',price:'$2.39',picUrl:require('../pages/menu/pics/McDonald-Ind-12.png').default,desc:''},
																									{name:'McDouble [380.0 Cals]',price:'$3.09',picUrl:require('../pages/menu/pics/McDonald-Ind-13.png').default,desc:''},
																									{name:'BLT with Crispy Chicken [690.0 Cals]',price:'$8.49',picUrl:require('../pages/menu/pics/McDonald-Ind-14.png').default,desc:''},
																									{name:'BLT with Grilled Chicken [560.0 Cals]',price:'$8.49',picUrl:require('../pages/menu/pics/McDonald-Ind-15.png').default,desc:''},
																									{name:'Spicy Habanero McChicken [470.0 Cals]',price:'$7.09',picUrl:require('../pages/menu/pics/McDonald-Ind-16.png').default,desc:''},
																									{name:'McChicken [480.0 Cals]',price:'$6.79',picUrl:require('../pages/menu/pics/McDonald-Ind-17.png').default,desc:''},
																									{name:'6 Chicken McNuggets [250.0 Cals]',price:'$6.79',picUrl:require('../pages/menu/pics/McDonald-Ind-18.png').default,desc:''},
																									{name:'10 Chicken McNuggets [410.0 Cals]',price:'$8.79',picUrl:require('../pages/menu/pics/McDonald-Ind-19.png').default,desc:''},
																									{name:'20 Chicken McNuggets (Serves 2) [830.0 Cals]',price:'$13.39',picUrl:require('../pages/menu/pics/McDonald-Ind-20.png').default,desc:''},
																									{name:'Filet-O-Fish [400.0 Cals]',price:'$6.79',picUrl:require('../pages/menu/pics/McDonald-Ind-21.png').default,desc:''},
																									{name:'Double Filet-O-Fish [570.0 Cals]',price:'$8.79',picUrl:require('../pages/menu/pics/McDonald-Ind-22.png').default,desc:''},
																									{name:'Ranch Chicken Snack Wrap with Grilled Chicken [250.0 Cals]',price:'$3.09',picUrl:require('../pages/menu/pics/McDonald-Ind-23.png').default,desc:''},
																									{name:'Ranch Chicken Snack Wrap with Crispy Chicken [320.0 Cals]',price:'$3.09',picUrl:require('../pages/menu/pics/McDonald-Ind-24.png').default,desc:''},
																									{name:'Junior Chicken [380.0 Cals]',price:'$2.69',picUrl:require('../pages/menu/pics/McDonald-Ind-25.png').default,desc:''},
																									]},
							]},
		{id:8,name:"Arch Noodle",restFilters:['Asian','Capmus','$$',''],thumbnailUrl: require('../pages/menu/pics/Arch-noodle.jpg').default, posterUrl: require('../pages/menu/pics/Arch-Noodle-Poster.png').default, footerImg:require('../pages/menu/pics/Arch-Noodle-Poster.png').default,
				descriptions:"Best Noodle here",
				address:'1309 Main St W, Hamilton, ON L8S 1C5', phoneNum:'(905) 525-8088',openHours:'Mon - Thurs: 11:00am - 11:00pm\nFri: 11:00am - 11:00pm\nSat - Sun: 11:00am - 11:00pm',
				menu:[{category:'',foods:[{name:'',picUrl:'',desc:''}]}]},
		{id:9,name:"Popeyes Chicken",restFilters:['Fast Food','Downtown','$',''],thumbnailUrl: require('../pages/menu/pics/Popeyes.jpg').default, posterUrl: require('../pages/menu/pics/popeyes-poster.jpg').default, footerImg:require('../pages/menu/pics/popeyes-poster.jpg').default,
			descriptions:"So fast, you get your chicken before you get your change",
			address:'11 King St E, Hamilton, ON L8N 1A1', phoneNum:'(905) 523-1212',openHours:'Mon - Thurs: 11:00am - 11:00pm\nFri: 11:00am - 11:00pm\nSat - Sun: 11:00am - 11:00pm',
			menu:[{category:'',foods:[{name:'',picUrl:'',desc:''}]}]},
	],
	allReviews:[{resName:'The Chopped Leaf',
								reviews:[{id:0,name:'Peter',starRate:5,profile:'',comments:'Good',Rdishes:['popeye','spa',''],like:23,likeStatus:false,dislikeStatus:false,dislike:2,date:'12/08/2020, 12:30:12'},
												{id:1,name:'Jason',starRate:4,profile:'',comments:'Not bad',Rdishes:['sunshine','spa',''],like:15,likeStatus:false,dislikeStatus:false,dislike:1,date:'15/09/2020, 15:12:15'},
												{id:2,name:'Alice',starRate:5,profile:'',comments:'Love it',Rdishes:['','',''],like:7,likeStatus:false,dislikeStatus:false,dislike:0,date:'16/09/2020, 18:20:54'},
												{id:3,name:'Mary',starRate:2,profile:'',comments:'Too expensive',Rdishes:['','',''],like:0,likeStatus:false,dislikeStatus:false,dislike:0,date:'10/09/2020, 11:08:02'},
												]},
							{resName:'TacoBell',reviews:[]},
							{resName:'Saigon',reviews:[]},
							{resName:'Bistro',reviews:[]},
							{resName:"Valentino's Restaurant",reviews:[]},
							{resName:'KenzoRamen',reviews:[]},
							{resName:'DragonCourt',reviews:[]},
							{resName:'McDonald',reviews:[{id:0,name:'Peter',starRate:5,profile:'',comments:'Great Service',Rdishes:['Big Mac [560.0 Cals]','',''],like:10,likeStatus:false,dislikeStatus:false,dislike:1,date:'12/09/2020, 12:30:12'},
																					{id:1,name:'Jason',starRate:5,profile:'',comments:'Love the food here',Rdishes:['Oreo McFlurry [330.0 Cals]','Coca-Cola [100.0 Cals]',''],like:5,likeStatus:false,dislikeStatus:false,dislike:0,date:'15/09/2020, 15:12:15'},
																					{id:2,name:'Alice',starRate:4,profile:'',comments:'Not Bad',Rdishes:['','',''],like:1,likeStatus:false,dislikeStatus:false,dislike:0,date:'16/09/2020, 18:20:54'},
																					{id:3,name:'Mary',starRate:2,profile:'',comments:'Fake Food',Rdishes:['','',''],like:0,likeStatus:false,dislikeStatus:false,dislike:0,date:'19/09/2020, 11:08:02'},
																					]},
							{resName:'ss',reviews:[]},
							{resName:'aa',reviews:[]}],
	nopicUrl:require('../pages/menu/pics/nopic.jpg').default,
	nonepicUrl:require('../pages/menu/pics/nonepic.jpg').default,
	reservations:{},
	subscriptions:{},
	CurrentPromo:[{
		code: "INV10KK",
		requirement: "",
		title: "Save $10",
		location: "Anywhere",
		category: "No limit",
		deadline: "Nov.23rd, 2020",
		amount: 3,
		expired: -1,
	}]
}

export default Common

/*



*/